apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: peoplesaver-farrellsoft-dev
  namespace: peoplesaver

spec:
  secretName: peoplesaver-farrellsoft-dev-tls
  issuerRef:
    name: peoplesaver-issuer-production
    kind: Issuer
  dnsNames:
    - peoplesaver.farrellsoft.dev