apiVersion: v1
kind: Service
metadata:
  name: peoplesaver-service
  namespace: peoplesaver
  labels:
    app: peoplesaver

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: peoplesaver